




/*
     FILE ARCHIVED ON 7:42:41 Okt 8, 2013 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 8:36:00 Okt 8, 2013.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
function Za(a){throw a;}
var Zb=void 0,Zc=!0,Zd=null,Ze=!1,Z,Zaa=Zaa||{},Zf=this,Zba=function(a){for(var a=a.split("."),b=Zf,c;c=a.shift();)if(b[c]!=Zd)b=b[c];else return Zd;return b},Zca=function(){},Zg=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";
if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},Zda=function(a){var b=Zg(a);return"array"==b||"object"==b&&"number"==typeof a.length},Zh=function(a){return"string"==typeof a},Zea=function(a){var b=typeof a;return"object"==b&&a!=Zd||"function"==b},Zha=function(a){return a[Zfa]||(a[Zfa]=++Zga)},Zfa="closure_uid_"+
Math.floor(2147483648*Math.random()).toString(36),Zga=0,Zia=function(a,b,c){return a.call.apply(a.bind,arguments)},Zja=function(a,b,c){a||Za(Error());if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},Zi=function(a,b,c){Zi=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?Zia:Zja;
return Zi.apply(Zd,arguments)},Zka=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}},Zla=Date.now||function(){return+new Date},Zj=function(a,b){var c=a.split("."),d=Zf;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&b!==Zb?d[e]=b:d=d[e]?d[e]:d[e]={}},Zk=function(a,b){function c(){}c.prototype=b.prototype;a.z=b.prototype;a.prototype=
new c};Function.prototype.bind=Function.prototype.bind||function(a,b){if(1<arguments.length){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,a);return Zi.apply(Zd,c)}return Zi(this,a)};var Zma=function(a){Error.captureStackTrace?Error.captureStackTrace(this,Zma):this.stack=Error().stack||"";a&&(this.message=""+a)};Zk(Zma,Error);Zma.prototype.name="CustomError";var Zl=function(a,b){for(var c=1;c<arguments.length;c++)var d=(""+arguments[c]).replace(/\$/g,"$$$$"),a=a.replace(/\%s/,d);return a},Zm=function(a){if(!Zna.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Zoa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Zpa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Zqa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Zra,"&quot;"));return a},Zoa=/&/g,Zpa=/</g,Zqa=/>/g,Zra=/\"/g,Zna=/[&<>\"]/;var Zsa=function(a,b){b.unshift(a);Zma.call(this,Zl.apply(Zd,b));b.shift()};Zk(Zsa,Zma);Zsa.prototype.name="AssertionError";var Zn=function(a,b,c){if(!a){var d=Array.prototype.slice.call(arguments,2),e="Assertion failed";if(b)var e=e+(": "+b),f=d;Za(new Zsa(""+e,f||[]))}},Zta=function(a,b){Za(new Zsa("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1)))};var Zo=Array.prototype,Zua=Zo.indexOf?function(a,b,c){Zn(a.length!=Zd);return Zo.indexOf.call(a,b,c)}:function(a,b,c){c=c==Zd?0:0>c?Math.max(0,a.length+c):c;if(Zh(a))return!Zh(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Zva=Zo.forEach?function(a,b,c){Zn(a.length!=Zd);Zo.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Zh(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Zwa=Zo.filter?function(a,b,c){Zn(a.length!=Zd);return Zo.filter.call(a,
b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=Zh(a)?a.split(""):a,h=0;h<d;h++)if(h in g){var i=g[h];b.call(c,i,h,a)&&(e[f++]=i)}return e},Zp=function(a,b){return 0<=Zua(a,b)},Zxa=function(a,b){var c=Zua(a,b);0<=c&&(Zn(a.length!=Zd),Zo.splice.call(a,c,1))},Zya=function(a){return Zo.concat.apply(Zo,arguments)},Zza=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},ZBa=function(a,b,c,d){Zn(a.length!=Zd);Zo.splice.apply(a,ZAa(arguments,1))},ZAa=function(a,
b,c){Zn(a.length!=Zd);return 2>=arguments.length?Zo.slice.call(a,b):Zo.slice.call(a,b,c)};var Zq=function(a,b){this.width=a;this.height=b};Zq.prototype.la=function(){return new Zq(this.width,this.height)};Zq.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};Zq.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};Zq.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};var ZCa=function(a,b){for(var c in a)b.call(Zb,a[c],c,a)},ZDa=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b},ZEa=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b},ZFa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),ZGa=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<ZFa.length;f++)c=ZFa[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var Zr,ZHa,ZIa,ZJa,ZKa=function(){return Zf.navigator?Zf.navigator.userAgent:Zd};ZJa=ZIa=ZHa=Zr=Ze;var ZLa;if(ZLa=ZKa()){var ZMa=Zf.navigator;Zr=0==ZLa.indexOf("Opera");ZHa=!Zr&&-1!=ZLa.indexOf("MSIE");ZIa=!Zr&&-1!=ZLa.indexOf("WebKit");ZJa=!Zr&&!ZIa&&"Gecko"==ZMa.product}var ZNa=Zr,Zs=ZHa,Zt=ZJa,Zu=ZIa,ZOa=Zf.navigator,ZPa=-1!=(ZOa&&ZOa.platform||"").indexOf("Win"),ZQa;
a:{var ZRa="",ZSa;if(ZNa&&Zf.opera)var ZTa=Zf.opera.version,ZRa="function"==typeof ZTa?ZTa():ZTa;else if(Zt?ZSa=/rv\:([^\);]+)(\)|;)/:Zs?ZSa=/MSIE\s+([^\);]+)(\)|;)/:Zu&&(ZSa=/WebKit\/(\S+)/),ZSa)var ZUa=ZSa.exec(ZKa()),ZRa=ZUa?ZUa[1]:"";if(Zs){var ZVa,ZWa=Zf.document;ZVa=ZWa?ZWa.documentMode:Zb;if(ZVa>parseFloat(ZRa)){ZQa=""+ZVa;break a}}ZQa=ZRa}
var ZXa=ZQa,ZYa={},Zv=function(a){var b;if(!(b=ZYa[a])){b=0;for(var c=(""+ZXa).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=(""+a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"",i=RegExp("(\\d*)(\\D*)","g"),j=RegExp("(\\d*)(\\D*)","g");do{var k=i.exec(g)||["","",""],l=j.exec(h)||["","",""];if(0==k[0].length&&0==l[0].length)break;b=((0==k[1].length?0:parseInt(k[1],10))<(0==l[1].length?0:parseInt(l[1],10))?-1:(0==k[1].length?
0:parseInt(k[1],10))>(0==l[1].length?0:parseInt(l[1],10))?1:0)||((0==k[2].length)<(0==l[2].length)?-1:(0==k[2].length)>(0==l[2].length)?1:0)||(k[2]<l[2]?-1:k[2]>l[2]?1:0)}while(0==b)}b=ZYa[a]=0<=b}return b},ZZa={},Zw=function(a){return ZZa[a]||(ZZa[a]=Zs&&!!document.documentMode&&document.documentMode>=a)};var Z_a=!Zs||Zw(9),Z0a=!Zt&&!Zs||Zs&&Zw(9)||Zt&&Zv("1.9.1"),Z1a=Zs&&!Zv("9");var Zx=function(a){a=a.className;return Zh(a)&&a.match(/\S+/g)||[]},Z2a=function(a,b){for(var c=Zx(a),d=ZAa(arguments,1),e=c.length+d.length,f=c,g=0;g<d.length;g++)Zp(f,d[g])||f.push(d[g]);a.className=c.join(" ");return c.length==e},Z3a=function(a,b,c){for(var d=Zx(a),e=Ze,f=0;f<d.length;f++)d[f]==b&&(ZBa(d,f--,1),e=Zc);e&&(d.push(c),a.className=d.join(" "))};var Zy=function(a){return Zh(a)?document.getElementById(a):a},Z4a=function(a,b,c){var d=document,c=c||d,a=a&&"*"!=a?a.toUpperCase():"";if(c.querySelectorAll&&c.querySelector&&(a||b))return c.querySelectorAll(a+(b?"."+b:""));if(b&&c.getElementsByClassName){c=c.getElementsByClassName(b);if(a){for(var d={},e=0,f=0,g;g=c[f];f++)a==g.nodeName&&(d[e++]=g);d.length=e;return d}return c}c=c.getElementsByTagName(a||"*");if(b){d={};for(f=e=0;g=c[f];f++)a=g.className,"function"==typeof a.split&&Zp(a.split(/\s+/),
b)&&(d[e++]=g);d.length=e;return d}return c},Z5a={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",maxlength:"maxLength",type:"type"},Z6a=function(a){a=a.document;a="CSS1Compat"==a.compatMode?a.documentElement:a.body;return new Zq(a.clientWidth,a.clientHeight)},Zz=function(a,b,c){return Z7a(document,arguments)},Z7a=function(a,b){var c=b[0],d=b[1];if(!Z_a&&d&&(d.name||d.type)){c=
["<",c];d.name&&c.push(' name="',Zm(d.name),'"');if(d.type){c.push(' type="',Zm(d.type),'"');var e={};ZGa(e,d);d=e;delete d.type}c.push(">");c=c.join("")}var f=a.createElement(c);d&&(Zh(d)?f.className=d:"array"==Zg(d)?Z2a.apply(Zd,[f].concat(d)):ZCa(d,function(a,b){"style"==b?f.style.cssText=a:"class"==b?f.className=a:"for"==b?f.htmlFor=a:b in Z5a?f.setAttribute(Z5a[b],a):0==b.lastIndexOf("aria-",0)?f.setAttribute(b,a):f[b]=a}));2<b.length&&Z8a(a,f,b,2);return f},Z8a=function(a,b,c,d){function e(c){c&&
b.appendChild(Zh(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var f=c[d];if(Zda(f)&&!(Zea(f)&&0<f.nodeType)){var g=Zva,h;a:{if((h=f)&&"number"==typeof h.length){if(Zea(h)){h="function"==typeof h.item||"string"==typeof h.item;break a}if("function"==Zg(h)){h="function"==typeof h.item;break a}}h=Ze}g(h?Zza(f):f,e)}else e(f)}},Z9a=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)},Z$a={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},Zab={IMG:" ",BR:"\n"},Zcb=function(a){if(Z1a&&"innerText"in
a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];Zbb(a,b,Zc);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");Z1a||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a},Zbb=function(a,b,c){if(!(a.nodeName in Z$a))if(3==a.nodeType)c?b.push((""+a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in Zab)b.push(Zab[a.nodeName]);else for(a=a.firstChild;a;)Zbb(a,b,c),a=a.nextSibling},Zdb=function(a){this.Fa=a||Zf.document||
document};Z=Zdb.prototype;Z.zc=function(a,b,c){return Z7a(this.Fa,arguments)};Z.createElement=function(a){return this.Fa.createElement(a)};Z.createTextNode=function(a){return this.Fa.createTextNode(a)};Z.appendChild=function(a,b){a.appendChild(b)};Z.append=function(a,b){Z8a(9==a.nodeType?a:a.ownerDocument||a.document,a,arguments,1)};Z.Tb=function(a){return Z0a&&a.children!=Zb?a.children:Zwa(a.childNodes,function(a){return 1==a.nodeType})};var Zeb="StopIteration"in Zf?Zf.StopIteration:Error("StopIteration"),Zfb=function(){};Zfb.prototype.next=function(){Za(Zeb)};Zfb.prototype.Sc=function(){return this};var Zgb=function(a){if("function"==typeof a.B)return a.B();if(Zh(a))return a.split("");if(Zda(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return ZDa(a)},Zhb=function(a){if("function"==typeof a.J)return a.J();if("function"!=typeof a.B){if(Zda(a)||Zh(a)){for(var b=[],a=a.length,c=0;c<a;c++)b.push(c);return b}return ZEa(a)}},Zib=function(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(Zda(a)||Zh(a))Zva(a,b,c);else for(var d=Zhb(a),e=Zgb(a),f=e.length,g=0;g<f;g++)b.call(c,
e[g],d&&d[g],a)};var ZA=function(a,b){this.w={};this.i=[];var c=arguments.length;if(1<c){c%2&&Za(Error("Uneven number of arguments"));for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof ZA?(c=a.J(),d=a.B()):(c=ZEa(a),d=ZDa(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};Z=ZA.prototype;Z.b=0;Z.ia=0;Z.B=function(){Zjb(this);for(var a=[],b=0;b<this.i.length;b++)a.push(this.w[this.i[b]]);return a};Z.J=function(){Zjb(this);return this.i.concat()};Z.N=function(a){return ZB(this.w,a)};
Z.clear=function(){this.w={};this.ia=this.b=this.i.length=0};Z.remove=function(a){return ZB(this.w,a)?(delete this.w[a],this.b--,this.ia++,this.i.length>2*this.b&&Zjb(this),Zc):Ze};var Zjb=function(a){if(a.b!=a.i.length){for(var b=0,c=0;b<a.i.length;){var d=a.i[b];ZB(a.w,d)&&(a.i[c++]=d);b++}a.i.length=c}if(a.b!=a.i.length){for(var e={},c=b=0;b<a.i.length;)d=a.i[b],ZB(e,d)||(a.i[c++]=d,e[d]=1),b++;a.i.length=c}};ZA.prototype.get=function(a,b){return ZB(this.w,a)?this.w[a]:b};
ZA.prototype.set=function(a,b){ZB(this.w,a)||(this.b++,this.i.push(a),this.ia++);this.w[a]=b};ZA.prototype.la=function(){return new ZA(this)};ZA.prototype.Sc=function(a){Zjb(this);var b=0,c=this.i,d=this.w,e=this.ia,f=this,g=new Zfb;g.next=function(){for(;;){e!=f.ia&&Za(Error("The map has changed since the iterator was created"));b>=c.length&&Za(Zeb);var g=c[b++];return a?g:d[g]}};return g};var ZB=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var Zlb=function(a){return Zkb(a||arguments.callee.caller,[])},Zkb=function(a,b){var c=[];if(Zp(b,a))c.push("[...circular reference...]");else if(a&&50>b.length){c.push(Zmb(a)+"(");for(var d=a.arguments,e=0;e<d.length;e++){0<e&&c.push(", ");var f;f=d[e];switch(typeof f){case "object":f=f?"object":"null";break;case "string":break;case "number":f=""+f;break;case "boolean":f=f?"true":"false";break;case "function":f=(f=Zmb(f))?f:"[fn]";break;default:f=typeof f}40<f.length&&(f=f.substr(0,40)+"...");c.push(f)}b.push(a);
c.push(")\n");try{c.push(Zkb(a.caller,b))}catch(g){c.push("[exception trying to get caller]\n")}}else a?c.push("[...long stack...]"):c.push("[end]");return c.join("")},Zmb=function(a){if(Znb[a])return Znb[a];a=""+a;if(!Znb[a]){var b=/function ([^\(]+)/.exec(a);Znb[a]=b?b[1]:"[Anonymous]"}return Znb[a]},Znb={};var Zob=function(a,b,c,d,e){this.reset(a,b,c,d,e)};Zob.prototype.Pb=Zd;Zob.prototype.Ob=Zd;var Zpb=0;Zob.prototype.reset=function(a,b,c,d,e){"number"==typeof e||Zpb++;d||Zla();this.ka=a;this.Dc=b;delete this.Pb;delete this.Ob};Zob.prototype.Ub=function(a){this.ka=a};var ZC=function(a){this.Nc=a};ZC.prototype.Ha=Zd;ZC.prototype.ka=Zd;ZC.prototype.fb=Zd;ZC.prototype.Vb=Zd;var Zqb=function(a,b){this.name=a;this.value=b};Zqb.prototype.toString=function(){return this.name};var Zrb=new Zqb("SEVERE",1E3),Zsb=new Zqb("WARNING",900),Ztb=new Zqb("CONFIG",700),Zub=new Zqb("FINE",500);ZC.prototype.getParent=function(){return this.Ha};ZC.prototype.Tb=function(){this.fb||(this.fb={});return this.fb};ZC.prototype.Ub=function(a){this.ka=a};
var Zvb=function(a){if(a.ka)return a.ka;if(a.Ha)return Zvb(a.Ha);Zta("Root logger has no level set.");return Zd};ZC.prototype.log=function(a,b,c){if(a.value>=Zvb(this).value){a=this.Oc(a,b,c);b="log:"+a.Dc;Zf.console&&(Zf.console.timeStamp?Zf.console.timeStamp(b):Zf.console.markTimeline&&Zf.console.markTimeline(b));Zf.msWriteProfilerMark&&Zf.msWriteProfilerMark(b);for(b=this;b;){var c=b,d=a;if(c.Vb)for(var e=0,f=Zb;f=c.Vb[e];e++)f(d);b=b.getParent()}}};
ZC.prototype.Oc=function(a,b,c){var d=new Zob(a,""+b,this.Nc);if(c){d.Pb=c;var e;var f=arguments.callee.caller;try{var g;var h=Zba("window.location.href");if(Zh(c))g={message:c,name:"Unknown error",lineNumber:"Not available",fileName:h,stack:"Not available"};else{var i,j,k=Ze;try{i=c.lineNumber||c.cd||"Not available"}catch(l){i="Not available",k=Zc}try{j=c.fileName||c.filename||c.sourceURL||h}catch(n){j="Not available",k=Zc}g=k||!c.lineNumber||!c.fileName||!c.stack?{message:c.message,name:c.name,
lineNumber:i,fileName:j,stack:c.stack||"Not available"}:c}e="Message: "+Zm(g.message)+'\nUrl: <a href="view-source:'+g.fileName+'" target="_new">'+g.fileName+"</a>\nLine: "+g.lineNumber+"\n\nBrowser stack:\n"+Zm(g.stack+"-> ")+"[end]\n\nJS stack traversal:\n"+Zm(Zlb(f)+"-> ")}catch(m){e="Exception trying to expose exception! You win, we lose. "+m}d.Ob=e}return d};
var ZD=function(a,b){a.log(Zub,b,Zb)},Zwb={},Zxb=Zd,Zyb=function(a){Zxb||(Zxb=new ZC(""),Zwb[""]=Zxb,Zxb.Ub(Ztb));var b;if(!(b=Zwb[a])){b=new ZC(a);var c=a.lastIndexOf("."),d=a.substr(c+1),c=Zyb(a.substr(0,c));c.Tb()[d]=b;b.Ha=c;Zwb[a]=b}return b};var Zzb=function(){};Zzb.prototype.Sb=Ze;Zzb.prototype.ja=function(){this.Sb||(this.Sb=Zc,this.s())};Zzb.prototype.s=function(){this.Pc&&ZAb.apply(Zd,this.Pc);if(this.Yb)for(;this.Yb.length;)this.Yb.shift()()};var ZAb=function(a){for(var b=0,c=arguments.length;b<c;++b){var d=arguments[b];Zda(d)?ZAb.apply(Zd,d):d&&"function"==typeof d.ja&&d.ja()}};var ZBb=function(a){ZBb[" "](a);return a};ZBb[" "]=Zca;!Zs||Zw(9);var ZCb=!Zs||Zw(9),ZDb=Zs&&!Zv("8");!Zu||Zv("528");Zt&&Zv("1.9b")||Zs&&Zv("8")||ZNa&&Zv("9.5")||Zu&&Zv("528");Zt&&!Zv("8")||Zs&&Zv("9");var ZE=function(a,b){this.type=a;this.currentTarget=this.target=b};Zk(ZE,Zzb);Z=ZE.prototype;Z.s=function(){delete this.type;delete this.target;delete this.currentTarget};Z.L=Ze;Z.defaultPrevented=Ze;Z.Aa=Zc;Z.stopPropagation=function(){this.L=Zc};Z.preventDefault=function(){this.defaultPrevented=Zc;this.Aa=Ze};var ZF=function(a,b){a&&this.ta(a,b)};Zk(ZF,ZE);Z=ZF.prototype;Z.target=Zd;Z.relatedTarget=Zd;Z.offsetX=0;Z.offsetY=0;Z.clientX=0;Z.clientY=0;Z.screenX=0;Z.screenY=0;Z.button=0;Z.keyCode=0;Z.charCode=0;Z.ctrlKey=Ze;Z.altKey=Ze;Z.shiftKey=Ze;Z.metaKey=Ze;Z.Z=Zd;
Z.ta=function(a,b){var c=this.type=a.type;ZE.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(Zt){var e;a:{try{ZBb(d.nodeName);e=Zc;break a}catch(f){}e=Ze}e||(d=Zd)}}else"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=Zu||a.offsetX!==Zb?a.offsetX:a.layerX;this.offsetY=Zu||a.offsetY!==Zb?a.offsetY:a.layerY;this.clientX=a.clientX!==Zb?a.clientX:a.pageX;this.clientY=a.clientY!==Zb?a.clientY:a.pageY;this.screenX=
a.screenX||0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.state=a.state;this.Z=a;a.defaultPrevented&&this.preventDefault();delete this.L};Z.stopPropagation=function(){ZF.z.stopPropagation.call(this);this.Z.stopPropagation?this.Z.stopPropagation():this.Z.cancelBubble=Zc};
Z.preventDefault=function(){ZF.z.preventDefault.call(this);var a=this.Z;if(a.preventDefault)a.preventDefault();else if(a.returnValue=Ze,ZDb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};Z.s=function(){ZF.z.s.call(this);this.relatedTarget=this.currentTarget=this.target=this.Z=Zd};var ZEb=function(){},ZFb=0;Z=ZEb.prototype;Z.key=0;Z.T=Ze;Z.Mb=Ze;Z.ta=function(a,b,c,d,e,f){"function"==Zg(a)?this.Lb=Zc:a&&a.handleEvent&&"function"==Zg(a.handleEvent)?this.Lb=Ze:Za(Error("Invalid listener argument"));this.fa=a;this.tb=b;this.src=c;this.type=d;this.capture=!!e;this.Ua=f;this.Mb=Ze;this.key=++ZFb;this.T=Ze};Z.handleEvent=function(a){return this.Lb?this.fa.call(this.Ua||this.src,a):this.fa.handleEvent.call(this.fa,a)};var ZG={},ZH={},ZI={},ZJ={},ZK=function(a,b,c,d,e){if(b){if("array"==Zg(b)){for(var f=0;f<b.length;f++)ZK(a,b[f],c,d,e);return Zd}var d=!!d,g=ZH;b in g||(g[b]={b:0,q:0});g=g[b];d in g||(g[d]={b:0,q:0},g.b++);var g=g[d],h=Zha(a),i;g.q++;if(g[h]){i=g[h];for(f=0;f<i.length;f++)if(g=i[f],g.fa==c&&g.Ua==e){if(g.T)break;return i[f].key}}else i=g[h]=[],g.b++;var j=ZGb,k=ZCb?function(a){return j.call(k.src,k.key,a)}:function(a){a=j.call(k.src,k.key,a);if(!a)return a},f=k;f.src=a;g=new ZEb;g.ta(c,f,a,b,d,
e);c=g.key;f.key=c;i.push(g);ZG[c]=g;ZI[h]||(ZI[h]=[]);ZI[h].push(g);a.addEventListener?(a==Zf||!a.rb)&&a.addEventListener(b,f,d):a.attachEvent(b in ZJ?ZJ[b]:ZJ[b]="on"+b,f);return c}Za(Error("Invalid event type"))},ZHb=function(a,b,c,d,e){if("array"==Zg(b))for(var f=0;f<b.length;f++)ZHb(a,b[f],c,d,e);else{d=!!d;a:{f=ZH;if(b in f&&(f=f[b],d in f&&(f=f[d],a=Zha(a),f[a]))){a=f[a];break a}a=Zd}if(a)for(f=0;f<a.length;f++)if(a[f].fa==c&&a[f].capture==d&&a[f].Ua==e){ZIb(a[f].key);break}}},ZIb=function(a){if(ZG[a]){var b=
ZG[a];if(!b.T){var c=b.src,d=b.type,e=b.tb,f=b.capture;c.removeEventListener?(c==Zf||!c.rb)&&c.removeEventListener(d,e,f):c.detachEvent&&c.detachEvent(d in ZJ?ZJ[d]:ZJ[d]="on"+d,e);c=Zha(c);e=ZH[d][f][c];if(ZI[c]){var g=ZI[c];Zxa(g,b);0==g.length&&delete ZI[c]}b.T=Zc;e.yb=Zc;ZJb(d,f,c,e);delete ZG[a]}}},ZJb=function(a,b,c,d){if(!d.za&&d.yb){for(var e=0,f=0;e<d.length;e++)d[e].T?d[e].tb.src=Zd:(e!=f&&(d[f]=d[e]),f++);d.length=f;d.yb=Ze;0==f&&(delete ZH[a][b][c],ZH[a][b].b--,0==ZH[a][b].b&&(delete ZH[a][b],
ZH[a].b--),0==ZH[a].b&&delete ZH[a])}},ZLb=function(a,b,c,d,e){var f=1,b=Zha(b);if(a[b]){a.q--;a=a[b];a.za?a.za++:a.za=1;try{for(var g=a.length,h=0;h<g;h++){var i=a[h];i&&!i.T&&(f&=ZKb(i,e)!==Ze)}}finally{a.za--,ZJb(c,d,b,a)}}return Boolean(f)},ZKb=function(a,b){a.Mb&&ZIb(a.key);return a.handleEvent(b)},ZGb=function(a,b){if(!ZG[a])return Zc;var c=ZG[a],d=c.type,e=ZH;if(!(d in e))return Zc;var e=e[d],f,g;if(!ZCb){f=b||Zba("window.event");var h=Zc in e,i=Ze in e;if(h){if(0>f.keyCode||f.returnValue!=
Zb)return Zc;a:{var j=Ze;if(0==f.keyCode)try{f.keyCode=-1;break a}catch(k){j=Zc}if(j||f.returnValue==Zb)f.returnValue=Zc}}j=new ZF;j.ta(f,this);f=Zc;try{if(h){for(var l=[],n=j.currentTarget;n;n=n.parentNode)l.push(n);g=e[Zc];g.q=g.b;for(var m=l.length-1;!j.L&&0<=m&&g.q;m--)j.currentTarget=l[m],f&=ZLb(g,l[m],d,Zc,j);if(i){g=e[Ze];g.q=g.b;for(m=0;!j.L&&m<l.length&&g.q;m++)j.currentTarget=l[m],f&=ZLb(g,l[m],d,Ze,j)}}else f=ZKb(c,j)}finally{l&&(l.length=0),j.ja()}return f}d=new ZF(b,this);try{f=ZKb(c,
d)}finally{d.ja()}return f};var ZL=function(){};Zk(ZL,Zzb);Z=ZL.prototype;Z.rb=Zc;Z.Va=Zd;Z.addEventListener=function(a,b,c,d){ZK(this,a,b,c,d)};Z.removeEventListener=function(a,b,c,d){ZHb(this,a,b,c,d)};
Z.dispatchEvent=function(a){var b=a.type||a,c=ZH;if(b in c){if(Zh(a))a=new ZE(a,this);else if(a instanceof ZE)a.target=a.target||this;else{var d=a,a=new ZE(b,this);ZGa(a,d)}var d=1,e,c=c[b],b=Zc in c,f;if(b){e=[];for(f=this;f;f=f.Va)e.push(f);f=c[Zc];f.q=f.b;for(var g=e.length-1;!a.L&&0<=g&&f.q;g--)a.currentTarget=e[g],d&=ZLb(f,e[g],a.type,Zc,a)&&a.Aa!=Ze}if(Ze in c)if(f=c[Ze],f.q=f.b,b)for(g=0;!a.L&&g<e.length&&f.q;g++)a.currentTarget=e[g],d&=ZLb(f,e[g],a.type,Ze,a)&&a.Aa!=Ze;else for(e=this;!a.L&&
e&&f.q;e=e.Va)a.currentTarget=e,d&=ZLb(f,e,a.type,Ze,a)&&a.Aa!=Ze;a=Boolean(d)}else a=Zc;return a};Z.s=function(){ZL.z.s.call(this);var a,b=0,c=a==Zd;a=!!a;if(this==Zd)ZCa(ZI,function(d){for(var e=d.length-1;0<=e;e--){var f=d[e];if(c||a==f.capture)ZIb(f.key),b++}});else{var d=Zha(this);if(ZI[d])for(var d=ZI[d],e=d.length-1;0<=e;e--){var f=d[e];if(c||a==f.capture)ZIb(f.key),b++}}this.Va=Zd};var ZMb=function(a){a=""+a;if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x10-\x1f\x80-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}Za(Error("Invalid JSON string: "+a))},ZNb=function(a){return eval("("+a+")")};var ZOb=Zf.window;var ZPb=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([\\w\\d\\-\\u0100-\\uffff.%]*)(?::([0-9]+))?)?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$"),ZQb=Zu,ZRb=function(a,b){if(ZQb){ZQb=Ze;var c=Zf.location;if(c){var d=c.href;if(d&&(d=(d=ZRb(3,d))&&decodeURIComponent(d))&&d!=c.hostname)ZQb=Zc,Za(Error())}}return b.match(ZPb)[a]||Zd};var ZSb=function(){};ZSb.prototype.oa=Zd;var ZTb,ZUb=function(){};Zk(ZUb,ZSb);var ZWb=function(a){return(a=ZVb(a))?new ActiveXObject(a):new XMLHttpRequest},ZXb=function(a){var b={};ZVb(a)&&(b[0]=Zc,b[1]=Zc);return b},ZVb=function(a){if(!a.$b&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.$b=d}catch(e){}}Za(Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed"))}return a.$b};
ZTb=new ZUb;var ZM=function(a){this.headers=new ZA;this.O=a||Zd};Zk(ZM,ZL);ZM.prototype.k=Zyb("goog.net.XhrIo");var ZYb=/^https?$/i,ZZb=[],ZN=function(a,b,c,d,e,f){var g=new ZM;ZZb.push(g);b&&ZK(g,"complete",b);ZK(g,"ready",Zka(Z_b,g));f&&(g.$=Math.max(0,f));g.send(a,c,d,e)},Z_b=function(a){a.ja();Zxa(ZZb,a)};Z=ZM.prototype;Z.C=Ze;Z.e=Zd;Z.na=Zd;Z.Ja="";Z.hb="";Z.F="";Z.Ka=Ze;Z.ma=Ze;Z.Ia=Ze;Z.K=Ze;Z.$=0;Z.H=Zd;Z.ib="";Z.bc=Ze;
Z.send=function(a,b,c,d){this.e&&Za(Error("[goog.net.XhrIo] Object is active with another request"));b=b?b.toUpperCase():"GET";this.Ja=a;this.F="";this.hb=b;this.Ka=Ze;this.C=Zc;this.e=this.O?ZWb(this.O):ZWb(ZTb);this.na=this.O?this.O.oa||(this.O.oa=ZXb(this.O)):ZTb.oa||(ZTb.oa=ZXb(ZTb));this.e.onreadystatechange=Zi(this.gb,this);try{ZD(this.k,ZO(this,"Opening Xhr")),this.Ia=Zc,this.e.open(b,a,Zc),this.Ia=Ze}catch(e){ZD(this.k,ZO(this,"Error opening Xhr: "+e.message));Z0b(this,e);return}var a=c||
"",f=this.headers.la();d&&Zib(d,function(a,b){f.set(b,a)});"POST"==b&&!f.N("Content-Type")&&f.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");Zib(f,function(a,b){this.e.setRequestHeader(b,a)},this);this.ib&&(this.e.responseType=this.ib);"withCredentials"in this.e&&(this.e.withCredentials=this.bc);try{this.H&&(ZOb.clearTimeout(this.H),this.H=Zd),0<this.$&&(ZD(this.k,ZO(this,"Will abort after "+this.$+"ms if incomplete")),this.H=ZOb.setTimeout(Zi(this.ac,this),this.$)),ZD(this.k,
ZO(this,"Sending request")),this.ma=Zc,this.e.send(a),this.ma=Ze}catch(g){ZD(this.k,ZO(this,"Send error: "+g.message)),Z0b(this,g)}};Z.ac=function(){"undefined"!=typeof Zaa&&this.e&&(this.F="Timed out after "+this.$+"ms, aborting",ZD(this.k,ZO(this,this.F)),this.dispatchEvent("timeout"),this.abort(8))};var Z0b=function(a,b){a.C=Ze;a.e&&(a.K=Zc,a.e.abort(),a.K=Ze);a.F=b;Z1b(a);Z2b(a)},Z1b=function(a){a.Ka||(a.Ka=Zc,a.dispatchEvent("complete"),a.dispatchEvent("error"))};
ZM.prototype.abort=function(){this.e&&this.C&&(ZD(this.k,ZO(this,"Aborting")),this.C=Ze,this.K=Zc,this.e.abort(),this.K=Ze,this.dispatchEvent("complete"),this.dispatchEvent("abort"),Z2b(this))};ZM.prototype.s=function(){this.e&&(this.C&&(this.C=Ze,this.K=Zc,this.e.abort(),this.K=Ze),Z2b(this,Zc));ZM.z.s.call(this)};ZM.prototype.gb=function(){!this.Ia&&!this.ma&&!this.K?this.Ec():Z3b(this)};ZM.prototype.Ec=function(){Z3b(this)};
var Z3b=function(a){if(a.C&&"undefined"!=typeof Zaa)if(a.na[1]&&4==Z4b(a)&&2==Z5b(a))ZD(a.k,ZO(a,"Local request error detected and ignored"));else if(a.ma&&4==Z4b(a))ZOb.setTimeout(Zi(a.gb,a),0);else if(a.dispatchEvent("readystatechange"),4==Z4b(a)){ZD(a.k,ZO(a,"Request complete"));a.C=Ze;try{if(ZP(a))a.dispatchEvent("complete"),a.dispatchEvent("success");else{var b;try{b=2<Z4b(a)?a.e.statusText:""}catch(c){ZD(a.k,"Can not get status: "+c.message),b=""}a.F=b+" ["+Z5b(a)+"]";Z1b(a)}}finally{Z2b(a)}}},
Z2b=function(a,b){if(a.e){var c=a.e,d=a.na[0]?Zca:Zd;a.e=Zd;a.na=Zd;a.H&&(ZOb.clearTimeout(a.H),a.H=Zd);b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){a.k.log(Zrb,"Problem encountered resetting onreadystatechange: "+e.message,Zb)}}},ZP=function(a){var b=Z5b(a),c;a:switch(b){case 200:case 201:case 202:case 204:case 304:case 1223:c=Zc;break a;default:c=Ze}if(!c){if(b=0===b)a=ZRb(1,""+a.Ja),!a&&self.location&&(a=self.location.protocol,a=a.substr(0,a.length-1)),b=!ZYb.test(a?a.toLowerCase():
"");c=b}return c},Z4b=function(a){return a.e?a.e.readyState:0},Z5b=function(a){try{return 2<Z4b(a)?a.e.status:-1}catch(b){return a.k.log(Zsb,"Can not get status: "+b.message,Zb),-1}},Z6b=function(a){try{return a.e?a.e.responseText:""}catch(b){return ZD(a.k,"Can not get responseText: "+b.message),""}},ZQ=function(a){if(a.e)return ZMb(a.e.responseText)},Z7b=function(a){return Zh(a.F)?a.F:""+a.F},ZO=function(a,b){return b+" ["+a.hb+" "+a.Ja+" "+Z5b(a)+"]"};var Z9b=function(a,b){var c=1,d;c instanceof Zq?(d=c.height,c=c.width):(b==Zb&&Za(Error("missing height argument")),d=b);a.style.width=Z8b(c);a.style.height=Z8b(d)},Z8b=function(a){"number"==typeof a&&(a=Math.round(a)+"px");return a},Zac=function(a){var b;a:{b=9==a.nodeType?a:a.ownerDocument||a.document;if(b.defaultView&&b.defaultView.getComputedStyle&&(b=b.defaultView.getComputedStyle(a,Zd))){b=b.display||b.getPropertyValue("display")||"";break a}b=""}if("none"!=(b||(a.currentStyle?a.currentStyle.display:
Zd)||a.style&&a.style.display))return Z$b(a);b=a.style;var c=b.display,d=b.visibility,e=b.position;b.visibility="hidden";b.position="absolute";b.display="inline";a=Z$b(a);b.display=c;b.position=e;b.visibility=d;return a},Z$b=function(a){var b=a.offsetWidth,c=a.offsetHeight,d=Zu&&!b&&!c;return(b===Zb||d)&&a.getBoundingClientRect?(b=a.getBoundingClientRect(),Zs&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop),new Zq(b.right-
b.left,b.bottom-b.top)):new Zq(b,c)},ZR=function(a,b){a.style.display=b?"":"none"};var ZS=function(a,b,c){this.o=a||Zd;this.Lc=!!c},ZU=function(a){if(!a.f&&(a.f=new ZA,a.b=0,a.o))for(var b=a.o.split("&"),c=0;c<b.length;c++){var d=b[c].indexOf("="),e=Zd,f=Zd;0<=d?(e=b[c].substring(0,d),f=b[c].substring(d+1)):e=b[c];e=decodeURIComponent(e.replace(/\+/g," "));e=ZT(a,e);a.add(e,f?decodeURIComponent(f.replace(/\+/g," ")):"")}},Zbc=function(a){var b=Zhb(a);"undefined"==typeof b&&Za(Error("Keys are undefined"));for(var c=new ZS(Zd,0,Zb),a=Zgb(a),d=0;d<b.length;d++){var e=b[d],f=a[d];if("array"==
Zg(f)){var g=c;g.remove(e);0<f.length&&(g.o=Zd,g.f.set(ZT(g,e),Zza(f)),g.b+=f.length)}else c.add(e,f)}return c};Z=ZS.prototype;Z.f=Zd;Z.b=Zd;Z.add=function(a,b){ZU(this);this.o=Zd;var a=ZT(this,a),c=this.f.get(a);c||this.f.set(a,c=[]);c.push(b);this.b++;return this};Z.remove=function(a){ZU(this);a=ZT(this,a);return this.f.N(a)?(this.o=Zd,this.b-=this.f.get(a).length,this.f.remove(a)):Ze};Z.clear=function(){this.f=this.o=Zd;this.b=0};Z.N=function(a){ZU(this);a=ZT(this,a);return this.f.N(a)};
Z.J=function(){ZU(this);for(var a=this.f.B(),b=this.f.J(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};Z.B=function(a){ZU(this);var b=[];if(a)this.N(a)&&(b=Zya(b,this.f.get(ZT(this,a))));else for(var a=this.f.B(),c=0;c<a.length;c++)b=Zya(b,a[c]);return b};Z.set=function(a,b){ZU(this);this.o=Zd;a=ZT(this,a);this.N(a)&&(this.b-=this.f.get(a).length);this.f.set(a,[b]);this.b++;return this};Z.get=function(a,b){var c=a?this.B(a):[];return 0<c.length?c[0]:b};
Z.toString=function(){if(this.o)return this.o;if(!this.f)return"";for(var a=[],b=this.f.J(),c=0;c<b.length;c++)for(var d=b[c],e=encodeURIComponent(""+d),d=this.B(d),f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(""+d[f]));a.push(g)}return this.o=a.join("&")};Z.la=function(){var a=new ZS;a.o=this.o;this.f&&(a.f=this.f.la());return a};var ZT=function(a,b){var c=""+b;a.Lc&&(c=c.toLowerCase());return c};
ZS.prototype.extend=function(a){for(var b=0;b<arguments.length;b++)Zib(arguments[b],function(a,b){this.add(b,a)},this)};if(window.jstiming){window.jstiming.Wb={};window.jstiming.Qc=1;var Zcc=function(a,b,c){var d="";window.jstiming.pt&&(d+="&srt="+window.jstiming.pt,delete window.jstiming.pt);try{window.external&&window.external.tran?d+="&tran="+window.external.tran:window.gtbExternal&&window.gtbExternal.tran?d+="&tran="+window.gtbExternal.tran():window.chrome&&window.chrome.csi&&(d+="&tran="+window.chrome.csi().tran)}catch(e){}var f=window.chrome;if(f&&(f=f.loadTimes)){f().wasFetchedViaSpdy&&(d+="&p=s");if(f().wasNpnNegotiated){var d=
d+"&npn=1",g=f().npnNegotiatedProtocol;g&&(d+="&npnv="+(encodeURIComponent||escape)(g))}f().wasAlternateProtocolAvailable&&(d+="&apa=1")}var g=a.t,h=g.start,f=[],i;for(i in g)if("start"!=i&&h){var j;j=a.t[i];var k=a.t.start;j=j&&k?j-k:Zb;f.push(i+"."+j)}delete g.start;if(b)for(var l in b)d+="&"+l+"="+b[l];(b=c)||(b="https:"==document.location.protocol?"/web/20131008074241/https://csi.gstatic.com/csi":"/web/20131008074241/http://csi.gstatic.com/csi");a=[b,"?v=3","&s="+(window.jstiming.sn||"codesite")+"&action=",a.name,"",d,"&rt=",f.join(",")].join("");
if(!a)return"";var d=new Image,n=window.jstiming.Qc++;window.jstiming.Wb[n]=d;d.onload=d.onerror=function(){window.jstiming&&delete window.jstiming.Wb[n]};d.src=a;d=Zd;return a};window.jstiming.report=function(a,b,c){if("prerender"==document.webkitVisibilityState){var d=Ze,e=function(){if(!d){b?b.prerender="1":b={prerender:"1"};var f;"prerender"==document.webkitVisibilityState?f=Ze:(Zcc(a,b,c),f=Zc);f&&(d=Zc,document.removeEventListener("webkitvisibilitychange",e,Ze))}};document.addEventListener("webkitvisibilitychange",
e,Ze);return""}return Zcc(a,b,c)}};function Zdc(a,b){var c=a?Zbc(a):new ZS;b!==Ze&&c.set("token",CS_env.token);return c.toString()}function Zec(a,b,c){ZN(a,function(a){a=a.target;ZP(a)&&b(a)},"POST",Zdc(c))};function Zfc(a,b){Zec(CS_env.relativeBaseUrl+"/hosting/stars.do",Zka(Zgc,a),b)}function Zgc(a,b){var c=ZQ(b).starred;a.Fc.src=CS_env.assetHostPath+(c?"/images/star_on.gif":"/images/star_off.gif");a.Qb&&(a.Qb.innerHTML=c?a.Hc:a.Gc);a.Ic&&Zhc()}_CS_setStar=Zfc;
_CS_toggleStar=function(a,b,c,d,e,f,g,h){var i=-1!=a.src.indexOf("/images/star_off.gif")?1:0;a.src=CS_env.assetHostPath+(i?"/images/star_on.gif":"/images/star_off.gif");if(d){var j=document.getElementById(d);j&&(j.innerHTML=i?e:f)}if(g&&(d=document.getElementById(g)))if(g=parseInt(d.innerHTML,10),g=i?g+1:g-1,d.innerHTML=g,h&&(h=document.getElementById(h)))h.innerHTML=1==g?"":"s";a={Hc:e,Gc:f,Fc:a,Qb:j,Ic:c};b.starred=i;Zfc(a,b)};_CS_dismissCue=function(a){ZR(Zy("cue"),Ze);CS_env.token&&ZN(CS_env.relativeBaseUrl+"/hosting/cues.do",Zd,"POST",Zdc({cue_id:a}));return Ze};_hideID=function(a){ZR(Zy(a),Ze);return Ze};_showID=function(a){ZR(Zy(a),Zc);return Ze};_hideEl=function(a){ZR(a,Ze);return Ze};_showEl=function(a){ZR(a,Zc);return Ze};_showInstead=function(a,b){ZR(Zy(a),Zc);ZR(b,Ze);return Ze};_toggleHidden=function(a){for(;a;){if(Zp(Zx(a),"closed"))return Z3a(a,"closed","opened"),Ze;if(Zp(Zx(a),"opened"))return Z3a(a,"opened","closed"),Ze;a=a.parentNode}};
_toggleCollapse=function(a){for(;a;){if(Zp(Zx(a),"collapse"))return Z3a(a,"collapse","expand"),Ze;if(Zp(Zx(a),"expand"))return Z3a(a,"expand","collapse"),Ze;a=a.parentNode}};function Zic(){var a=/http:\/\/[^\/]*\/(u|hosting|r|p)\/([^\?\/]*)\/?([^\?\/]*)\/?([^\?\/]*)?/.exec(window.location.href);if("hosting"==a[1])return a[2]?"hosting_"+a[2]:"hosting_home";if("u"==a[1])return"updates"==a[3]?a[4]?"user_updates_"+a[4]:"user_updates_user":"user_profile";if("p"==a[1]||"r"==a[1]){if(!a[3]&&!a[4])return"summary";if("wiki"==a[3]||a[3]&&!a[4])return a[3];if(a[3]&&a[4])return("w"==a[3]?"wiki":a[3])+"_"+a[4]}return"other"}
function Zjc(){var a=window.jstiming.load;a.tick("plt");var b=["codesite","ph"],c="project_"+Zic();b.push(c);a.name=b.join(",");window.setTimeout(function(){window.jstiming.report(a)},500)}_CS_reportToCsi=function(){window.attachEvent?window.attachEvent("onload",Zjc):window.addEventListener&&window.addEventListener("load",Zjc,Ze)};function Zkc(a){window.setTimeout(function(){_gaq.push("siteTracker._trackPageview",a)},0)}_CS_click=Zkc;var ZW=function(a,b){this.xa=Zlc.length;Zlc[this.xa]=this;this.target=a;this.Wa=b||Zd;this.X=a;this.m=[];this.ha=[];this.h=this.createElement("div","menuDiv instance"+this.xa);this.Ya=this.target.getAttribute("id");this.h.setAttribute("id",this.Ya!=Zd?"menuDiv-"+this.Ya:"menuDiv-instance"+this.xa);this.ua();Zmc(this,"default");ZV(this.X,"click",Znc(this,this.toggle));ZV(window,"resize",Znc(this,this.sb));ZV(document,"click",Znc(this,this.ua));ZV(this.h,"click",this.stopPropagation());ZV(this.X,"click",
this.stopPropagation())};Z=ZW.prototype;Z.target=Zd;Z.Ya=Zd;Z.X=Zd;Z.h=Zd;Z.Wa=Zd;Z.d=Zd;Z.xa=-1;Z.m=Zd;Z.ha=Zd;Z.createElement=function(a,b,c){a=document.createElement(a);a.className=b;c&&this.append(c,a);return a};
var ZV=function(a,b,c){if(a.addEventListener)a.addEventListener(b,c,Ze);else try{a.attachEvent("on"+b,c)}catch(d){a["on"+b]=c}},Znc=function(a,b){return function(){b.apply(a)}},Zmc=function(a,b,c){a.d=a.d||[];var d=a.createElement("div","menuCategory "+b);d.qb=b;c&&(c=a.createElement("b","categoryTitle "+b,c),c.style.display="block",a.append(c),d.$a=c);a.append(d);return a.d[a.d.length]=a.d[b]=d};
ZW.prototype.clear=function(){for(var a=0;a<this.d.length;a++)this.d[this.d[a].qb]=Zd;this.m.splice(0,this.m.length);this.d.splice(0,this.d.length);this.d=[];this.m=[];this.h.innerHTML=""};ZW.prototype.removeItem=function(a){for(var b=Zd,c=0;c<this.m.length;c++)this.m[c]==a&&(b=this.m[c],this.m.splice(c,1)),this.m[c].item.Za=c;return b};
var Zoc=function(a){var b=ZX;if((a=b.d[a])&&a.parentNode){a.$a&&a.$a.parentNode.removeChild(a.$a);a.parentNode.removeChild(a);for(var c=0;c<b.d.length;c++)if(b.d[c]===a){b.d[b.d[c].qb]=Zd;b.d.splice(c,1);return}for(c=0;c<a.childNodes.length;c++)a.childNodes[c].Za?b.m.splice(a.childNodes[c].Za,1):b.removeItem(a.childNodes[c])}},ZY=function(a,b,c,d,e){d=d?a.d[d]||Zmc(a,d,e):a.d["default"];c=c==Zb?"#":c;e=Zb;e=c?a.createElement("a","menuItem",b):a.createElement("span","menuText",b);b="string"==typeof b?
b:b.innerText||"ERROR";e.style.display="block";c&&e.setAttribute("href",c);e.Za=a.m.length;a.append(e,d);a.m[a.m.length]={item:e,text:b}},Zpc=function(a){var b=a.d.controls||Zmc(a,"controls",""),c=a.createElement("hr","menuSeparator");a.append(c,b)};Z=ZW.prototype;
Z.sb=function(){var a=this.h.style;a.position="absolute";for(var b=Zd,c=0;c<this.d.length;c++)this.d[c].className=this.d[c].className.replace(/ first/,""),0==this.d[c].childNodes.length?this.d[c].style.display="none":(this.d[c].style.display="",b||(b=this.d[c],b.className+=" first"));var d="none"!=a.display&&"hidden"!=a.visibility,b=document.documentElement.clientWidth,c=document.documentElement.clientHeight,b=(window.innerWidth||b&&0<b?b:document.body.clientWidth)||1,c=(window.innerHeight||c&&0<
c?c:document.body.clientHeight)||1,e=this.find(this.target),f=this.target.offsetWidth,g=this.target.offsetHeight,h=this.h.offsetWidth,i=this.h.offsetHeight;d||(d=a.visibility,i=a.display,a.visibility="hidden",a.display="",a.height="",a.width="",h=this.h.offsetWidth,a.display=i,a.visibility=d);(d=0.8<this.h.offsetHeight/c)?(i=parseInt(0.8*c,10),a.height=i+"px",a.overflowX="hidden",a.overflowY="auto"):a.height=a.overflowY=a.overflowX="";a.top=e.y+g+"px";a.left=e.x+"px";175>h&&(a.width="175px");d&&(a.width=
parseInt(a.width,10)+13+"px");e.x+h>b&&(a.left=e.x-(h-f)+"px")};Z.append=function(a,b){var c=b||this.h;"string"==typeof b&&this.d[b]&&(c=this.d[b]);"string"==typeof a?c.innerHTML+=a:c.appendChild(a)};Z.stopPropagation=function(){return function(a){a||(a=window.event);a.cancelBubble=Zc;a.stopPropagation&&a.stopPropagation()}};Z.toggle=function(){"none"==this.h.style.display?this.show():this.ua()};
Z.show=function(){if(""!=this.h.style.display){for(var a=0;a<this.ha.length;a++)this.ha[a].call(Zd,this);this.h.style.visibility="hidden";this.h.style.display="";this.sb();this.X.nodeName&&"A"==this.X.nodeName&&this.X.blur();this.h.style.visibility="visible";for(a=0;a<Zlc.length;a++){var b=Zlc[a];b!=this&&b.ua()}this.Wa&&this.Wa()}};Z.ua=function(){this.h.style.display="none"};
Z.find=function(a){var b=0,c=0;if(a.offsetParent){do b+=a.offsetLeft,c+=a.offsetTop;while((a=a.offsetParent)&&a.style&&"relative"!=a.style.position&&"absolute"!=a.style.position)}return{x:b,y:c}};var Zlc=[];var ZX,Zqc=document.getElementById("projects-dropdown");Zqc&&(ZX=new ZW(Zqc,function(){Zkc("/gb/ph/myprojects")}),ZV(window,"load",Zhc),ZX.ha.push(Zhc),ZV(window,"load",function(){document.body.appendChild(ZX.h)}));function Zhc(){CS_env.token?Zec(CS_env.relativeBaseUrl+"/hosting/projects",Zrc,{}):Zrc(Zd)}
function Zrc(a){if(a){var b=[],c=[],d=[],e=[],f=ZQ(a),g;for(g in f)switch(g){case "personal_projects":for(a=0;a<f[g].length;a++)b.push(f[g][a]);break;case "contributorto":case "memberof":case "ownerof":for(a=0;a<f[g].length;a++)c.push(f[g][a]);break;case "starred_projects":for(a=0;a<f[g].length;a++)d.push(f[g][a]);break;case "starred_products":for(a=0;a<f[g].length;a++)e.push(f[g][a]);break;case "playground_token":Zsc(f[g]);break;case "error":return}ZX.clear();b.sort();for(a=0;a<b.length;a++){g=CS_env.profileUrl+
"p/"+b[a]+"/";ZY(ZX,b[a],g,"personal_projects","Personal projects")}c.sort();for(a=0;a<c.length;a++){g=CS_env.relativeBaseUrl+"/p/"+c[a]+"/";ZY(ZX,c[a],g,"projects","Projects")}d.sort();for(a=0;a<d.length;a++){g=CS_env.relativeBaseUrl+"/p/"+d[a]+"/";ZY(ZX,d[a],g,"starred_projects","Starred projects")}if(window.Rc){e.sort();for(a=0;a<e.length;a++)(b=window.Rc[e[a]])&&(b.title&&b.url)&&ZY(ZX,b.title,b.url,"starred_products","Starred products")}Ztc(Zuc)}else{e=encodeURIComponent(window.location.href);
ZX.clear();ZY(ZX,"Sign in to see your favorites","/web/20131008074241/http://www.google.com/accounts/ServiceLogin?service=code&ltmpl=phosting&continue="+e+"&amp;followup="+e,"controls");Zvc()}}function Zvc(){Zpc(ZX);ZY(ZX,"Find developer products...","/more/","controls");ZY(ZX,"Find open source projects...","/hosting/","controls")}var Zuc=Zd;
function Zsc(a){ZN("/apis/ajax/playground/get_projects",function(a){a=a.target;if(ZP(a)){a=ZQ(a);if(a!=Zuc){Ztc(a);Zuc=a}}},"POST",Zdc({token:a,u:CS_env.loggedInUserEmail},Ze))}function Ztc(a){Zoc("playground_projects");Zoc("controls");if(a&&a.responseStatus=="200"&&a.numSamples>0)for(var b=0;b<a.samples.length;b++){var c=a.samples[b];ZY(ZX,c.sampleName,c.sampleLoc,"playground_projects","Playground Projects")}Zvc()};var ZZ,Zwc=document.getElementById("multilogin-dropdown");Zwc&&(ZZ=new ZW(Zwc,function(){Zkc("/gb/ph/multilogin")}),ZV(window,"load",Zxc),ZZ.ha.push(Zxc),ZV(window,"load",function(){document.body.appendChild(ZZ.h)}));function Zxc(){Zec("/hosting/multilogin",Zyc,{})}
function Zyc(a){var b=ZQ(a),a=b.sessions,b=b.active,c=encodeURIComponent(window.location.href);ZZ.clear();for(var d=window.location.href.replace(/#.*/,""),e=0;e<a.length;e++){var f=a[e].addr,g=d+(d.indexOf("?")==-1?"?":"&")+"authuser="+a[e].acct+window.location.hash,h=a[e].disabled;if(b==e){f="<b>"+f+"</b>";g=""}else if(h){f='<span style="color:gray" title="This session has been disabled">'+f+"</span>";g=""}ZY(ZZ,f,g)}Zpc(ZZ);ZY(ZZ,"<nobr>Sign in with another account...</nobr>","/web/20131008074241/http://www.google.com/accounts/AddSession?service=code&continue="+
c,"controls")};
